version: '2.1'
services:
    elasticsearch: 
        image: elasticsearch:6.4.2
        volumes:
            - ./es_data:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - es

    kibana:
        image: kibana:6.6.1
        ports:
            - 5601:5601
        environment:
            ELASTICSEARCH_URL: "http://elasticsearch:9200"
        networks:
            - es
        depends_on:
            - elasticsearch

networks:
    es:
        driver: bridge